# Use a slim version of Python 3.9
FROM --platform=linux/amd64 python:3.9-slim

# Set the working directory inside the container
WORKDIR /app

# Copy dependencies list into container
COPY requirements.txt .

# Install required Python packages
RUN pip install --no-cache-dir -r requirements.txt

# Copy your application code into the container
COPY app/ app/

# Run your main.py script
CMD ["python", "app/main.py"]
